//数据接收，数据发布

export const SETBASICINFOFIELDS = 'DI_SETBASICINFOFIELDS'//基本信息字段
export const SETDATAFORMAT = 'DI_SETDATAFORMAT' //数据格式
export const SETAPIARGUCOUNt = 'DI_SETAPIARGUCOUNT'
export const SETAPIARGUINFO = 'DI_SETAPIARGUINFO'
export const DELETEAPIARGUROW = 'DI_DELETEAPIARGUINFO'

export const SETDBCONLIST = 'DI_SETDBCONLIST'
export const SETTABLELIST = 'DI_SETTABLELLIST'
export const SETSETTABLEINFO = 'DI_SETTABLEINFO'
export const SETTARGETINFOS = 'DI_SETTARGETINFO'

export const SETFIELDSCONFIGCOUNT = 'DI_SETFIELDSCONFIGCOUNT'
export const SETFIELDCONFIGINFO = 'DI_SETFIELDCONFIGINFO'
export const DELETEFIELDCONFIGROW = 'DI_DELETEFIELDCONFIGROW';

export const SETDOCINFO = 'DI_SETDOCINFO'


export const SETSOURCEINFO = 'DI_SETSOURCEINFO'
export const SETINOUTARGU = 'DI_SETINOUTARGU'
export const SETPREVIEWINFO = 'DI_SETDATAPREVIEWINFO'

export const SETPREVIEWDATA = 'DI_SETPREVIEWDATA'